### ISSUE TITLE
Unable to read any keys via SSH tunnel

### ISSUE THREAD

**Issue by hannesvz** [mat2cc/redis_tui#2]
## Problem

Cannot read keys from remote redis server via SSH tunnel, with local port 30001.

## Details

I'm using this through an Ubuntu 20 WSL2 instance connecting via Windows Terminal. Remote redis server is a redis service running on a [Platform.sh](https://platform.sh) project.

## What I'm seeing

When connecting to my remote server through SSH tunnel with `redis_tui`, it does successfully connect, but finds 0 keys and shows a message "Whoops, no keys found for that search value". It also locks up my terminal, preventing any further commands and does not respond to any keystrokes.

## What I've tried

I can use `redis_tui` on a locally running redis server and it reads all keys successfully. ✅

I am also able to connect to my remote redis server through the SSH tunnel with my normal `redis-cli`, and other tools like redis-commander. ✅

Installing it locally on the server is unfortunately not possible, so this would be quite handy to have working through the tunnel.

**Comment by mat2cc** [comment]
Hey, I have not tried this use case personally. It does seem very useful though. I will try to find some time to implement this!

**Comment by hannesvz** [comment]
Nice! It's working through the SSH tunnel now, thanks for the fix! 👍
