### ISSUE TITLE
Feature: custom delimiter

### ISSUE THREAD

**Issue by sralloza** [mat2cc/redis_tui#5]
Hi have a proyect where we use "::" instead of ":" as a delimiter. I think that having a flag to set a custom delimiter (set [here](https://github.com/mat2cc/redis_tui/blob/59f26576995c1ab1029d96cc09c472b17adae1be/tui/node.go#L39)) would be awesome. Would you be open to implement this feature? Or accept a PR that implements it?

**Comment by mat2cc** [comment]
Hey! You're very welcome to submit a PR if you want to. It also seem like a straightforward (and very beneficial) feature to add. I will add it in the short term if you don't submit a PR

**Comment by sralloza** [comment]
Thanks for the feature! You weren't kidding with "short time" 😆
